/*
 * generated by Xtext 2.23.0
 */
package lego.rover.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MissionUiModule extends AbstractMissionUiModule {

	public MissionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
