/*
 * generated by Xtext 2.23.0
 */
package gameoflife.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gameoflife.GolRuntimeModule;
import gameoflife.GolStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GolIdeSetup extends GolStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GolRuntimeModule(), new GolIdeModule()));
	}
	
}
