/*
 * generated by Xtext 2.23.0
 */
package gameoflife.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GolUiModule extends AbstractGolUiModule {

	public GolUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
