/*
 * generated by Xtext 2.23.0
 */
package lego.rover.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import lego.rover.MissionRuntimeModule;
import lego.rover.MissionStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MissionIdeSetup extends MissionStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MissionRuntimeModule(), new MissionIdeModule()));
	}
	
}
